### ISSUE TITLE
Version numbers inconsistent 

### ISSUE THREAD

**Issue by mkillewald** [echolevel/bootPT#3]
A very small nitpick to an otherwise great custom build.  The name of the adf suggests this is version 2.3F while the version shown in intro2 text at boot up and also inside PT is 2.3E  

Merry Christmas!

**Comment by echolevel** [comment]
Thanks! Should all be sorted now :)

**Comment by djenzyme** [comment]
Again, its a really small thing, below the quadrascope in PT the version reads as 2.3E ;)
