### ISSUE TITLE
LHA of modded 2.3F for Workbench Installs

### ISSUE THREAD

**Issue by djhardrich** [echolevel/bootPT#5]
Hi, I love your patched PT2.3, is there any way we could get an LHA for running in workbench? Losing 300-400k chipram isn't the end of the world ;) Thanks!

**Comment by echolevel** [comment]
Glad you like it! Yeah, I'll try to get an LHA sorted and uploaded tonight. What's your hardware? If you're on a 1200 with some fast ram, both PT and later versions of Workbench will try to use fast ram as much as possible (everything except sampledata and graphics), so you shouldn't even lose as much as that!

**Comment by djhardrich** [comment]
Using a MiSTer with the Minimig core (A1200, 8mb Fast, 2mb Chip, 1.5mb Slow), everything is -solid- other than direct sampling (using a board with ADC set up in the core, will investigate)..... Almost good enough to get people to stop hoarding Amigas!

**Comment by echolevel** [comment]
Sorry that took me so long @djhardrich, but there's an LHA available now containing the executable, the bootPT config file and the chip-sample directory. Thanks for the suggestion!
